"""Small structured-output models produced by agents."""

from __future__ import annotations

from pydantic import BaseModel, Field


class PlanStepDraft(BaseModel):
    text: str
    acceptance_criteria: list[str] = Field(default_factory=list)

    model_config = {"frozen": True}


class PlannerOutput(BaseModel):
    steps: list[PlanStepDraft] = Field(default_factory=list)

    model_config = {"frozen": True}


class CoderOutput(BaseModel):
    source: str

    model_config = {"frozen": True}


class FinalizerOutput(BaseModel):
    answer: str

    model_config = {"frozen": True}


class AnalyzerScriptOutput(BaseModel):
    """The Python script generated by the two-step Analyzer for file parsing."""

    source: str

    model_config = {"frozen": True}


class SubQuestionDraft(BaseModel):
    """A single sub-question produced by the Sub-Question Generator (DS-STAR+)."""

    index: int
    text: str
    rationale: str = ""

    model_config = {"frozen": True}


class SubQuestionList(BaseModel):
    """Collection of sub-questions produced by the Sub-Question Generator."""

    questions: list[SubQuestionDraft] = Field(default_factory=list)

    model_config = {"frozen": True}


class ReportOutput(BaseModel):
    """Report produced by the Report Writer agent (DS-STAR+)."""

    markdown: str = Field(min_length=10)

    model_config = {"frozen": True}


__all__ = [
    "AnalyzerScriptOutput",
    "CoderOutput",
    "FinalizerOutput",
    "PlanStepDraft",
    "PlannerOutput",
    "ReportOutput",
    "SubQuestionDraft",
    "SubQuestionList",
]
